version: 2

models:
  - name: dim_hosts
    description: Cleansed table for the Airbnb hosts.

  - name: dim_listings
    description: Cleansed table which contains Airbnb listings.
    columns:
    - name: listing_id
      description: Unique identifier for the listing.
      tests:
        - unique
        - not_null
    - name: host_id
      description: Unique identifier for the host.
      tests:
        - not_null
        - relationships:
            to: ref('dim_hosts')
            field: host_id
     
    - name: room_type
      description: Type of room
      tests:
        - accepted_values:
            values: ['Entire home/apt',
                      'Private room',
                      'Shared room',
                      'Hotel room']
                      
    - name: minimum_nights
      description: '{{ doc("dim_listings_minimum_nights") }}'
      tests:
        - positive_value                  
  - name: dim_listings_w_hosts
    tests:
      - dbt_expectations.expect_table_row_count_to_equal_other_table:
          compare_model: source('airbnb_raw', 'listings_raw')

    columns:
      - name: price
        tests:
            - dbt_expectations.expect_column_values_to_be_of_type:
                column_type: FLOAT64
            - dbt_expectations.expect_column_quantile_values_to_be_between:
                quantile: .99
                min_value: 50 # (Optional)
                max_value: 500 # (Optional)
              

  - name: fct_reviews

  - name: mart_fullmoon_reviews

