name: 'airbnb_project'
version: '1.0.0'
profile: airbnb_project
config-version: 2


model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]


clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/
# directory as views. These settings can be overridden in the individual model
# files using the `{{ config(...) }}` macro.

models:
  airbnb_project:
      # every model is materialized as a view by default
      +materialized: view
      dim:
        +materialized: table
      src:
      # every model will created as cte to be used on the following model
        +materialized: ephemeral
